package models

type MainTable struct {
	ArriveTime               string `json:"arriveTime,omitempty"`
	AssistantName            string `json:"assistantName,omitempty"`
	AssistantNo              string `json:"assistantNo,omitempty"`
	BackHubei                string `json:"backHubei,omitempty"`
	BackTime                 string `json:"backTime,omitempty"`
	BackTransportation       string `json:"backTransportation,omitempty"`
	BackTransportationOther  string `json:"backTransportationOther,omitempty"`
	BackTransportationShift  string `json:"backTransportationShift,omitempty"`
	Birthday                 string `json:"birthday,omitempty"`
	ChooseType1              string `json:"chooseType1,omitempty"`
	ChooseType2              string `json:"chooseType2,omitempty"`
	CityArea                 string `json:"cityArea,omitempty"`
	ClassCode                string `json:"classCode,omitempty"`
	ClassName                string `json:"className,omitempty"`
	CollegeCode              string `json:"collegeCode,omitempty"`
	CollegeName              string `json:"collegeName,omitempty"`
	CountryArea              string `json:"countryArea,omitempty"`
	CreateTime               string `json:"createTime,omitempty"`
	CurrentArea              string `json:"currentArea,omitempty"`
	DeclareTime              string `json:"declareTime,omitempty"`
	Del                      string `json:"del,omitempty"`
	ID                       int    `json:"id,omitempty"`
	InChina                  string `json:"inChina,omitempty"`
	IsFamily                 string `json:"isFamily,omitempty"`
	IsFamilyState            string `json:"isFamilyState,omitempty"`
	IsNew                    string `json:"isNew,omitempty"`
	IsPass14C1               string `json:"isPass14C1,omitempty"`
	IsPass14C2               string `json:"isPass14C2,omitempty"`
	IsPass14C3               string `json:"isPass14C3,omitempty"`
	IsPassHb                 string `json:"isPassHb,omitempty"`
	IsSick1                  string `json:"isSick1,omitempty"`
	IsSick2                  string `json:"isSick2,omitempty"`
	IsSick3                  string `json:"isSick3,omitempty"`
	IsSick4                  string `json:"isSick4,omitempty"`
	IsSick5                  string `json:"isSick5,omitempty"`
	IsSick6                  string `json:"isSick6,omitempty"`
	IsSick7                  string `json:"isSick7,omitempty"`
	Language                 string `json:"language,omitempty"`
	LeaveHubei               string `json:"leaveHubei,omitempty"`
	LeaveState               string `json:"leaveState,omitempty"`
	LeaveTime                string `json:"leaveTime,omitempty"`
	LeaveTransportation      string `json:"leaveTransportation,omitempty"`
	LeaveTransportationOther string `json:"leaveTransportationOther,omitempty"`
	LeaveTransportationShift string `json:"leaveTransportationShift,omitempty"`
	Linkman                  string `json:"linkman,omitempty"`
	LinkmanPhone             string `json:"linkmanPhone,omitempty"`
	LinkmanPhoneArea         string `json:"linkmanPhoneArea,omitempty"`
	Other                    string `json:"other,omitempty"`
	OtherC1                  string `json:"otherC1,omitempty"`
	OtherC2                  string `json:"otherC2,omitempty"`
	OtherC3                  string `json:"otherC3,omitempty"`
	OtherC4                  string `json:"otherC4,omitempty"`
	OtherSick                string `json:"otherSick,omitempty"`
	PassArea                 string `json:"passArea,omitempty"`
	PassAreaC2               string `json:"passAreaC2,omitempty"`
	PassAreaC3               string `json:"passAreaC3,omitempty"`
	PassAreaC4               string `json:"passAreaC4,omitempty"`
	PersonC1                 string `json:"personC1,omitempty"`
	PersonC1ID               string `json:"personC1id,omitempty"`
	PersonC2                 string `json:"personC2,omitempty"`
	PersonC2ID               string `json:"personC2id,omitempty"`
	PersonC3                 string `json:"personC3,omitempty"`
	PersonC3ID               string `json:"personC3id,omitempty"`
	PersonC4                 string `json:"personC4,omitempty"`
	PersonHealth             string `json:"personHealth,omitempty"`
	PersonHealth2            string `json:"personHealth2,omitempty"`
	PersonName               string `json:"personName,omitempty"`
	PersonNo                 string `json:"personNo,omitempty"`
	PersonSick               string `json:"personSick,omitempty"`
	PersonState              string `json:"personState,omitempty"`
	PersonState2             string `json:"personState2,omitempty"`
	PersonType               string `json:"personType,omitempty"`
	Phone                    string `json:"phone,omitempty"`
	PhoneArea                string `json:"phoneArea,omitempty"`
	ProfessionName           string `json:"professionName,omitempty"`
	SchoolArea               string `json:"schoolArea,omitempty"`
	SchoolC1                 string `json:"schoolC1,omitempty"`
	SchoolC2                 string `json:"schoolC2,omitempty"`
	Sex                      string `json:"sex,omitempty"`
	Temperature              string `json:"temperature,omitempty"`
	Way2No                   string `json:"way2No,omitempty"`
	Way2Other                string `json:"way2Other,omitempty"`
	Way2Start                string `json:"way2Start,omitempty"`
	Way2Type1                string `json:"way2Type1,omitempty"`
	Way2Type2                string `json:"way2Type2,omitempty"`
	Way2Type3                string `json:"way2Type3,omitempty"`
	Way2Type4                string `json:"way2Type4,omitempty"`
	Way2Type5                string `json:"way2Type5,omitempty"`
	Way2Type6                string `json:"way2Type6,omitempty"`
	WayNo                    string `json:"wayNo,omitempty"`
	WayStart                 string `json:"wayStart,omitempty"`
	WayType1                 string `json:"wayType1,omitempty"`
	WayType2                 string `json:"wayType2,omitempty"`
	WayType3                 string `json:"wayType3,omitempty"`
	WayType4                 string `json:"wayType4,omitempty"`
	WayType5                 string `json:"wayType5,omitempty"`
	WayType6                 string `json:"wayType6,omitempty"`
	WayTypeOther             string `json:"wayTypeOther,omitempty"`
}
